function cellInfo = createBusActor(numActor, busName, busActorsActorsName) 
% CREATEBUSACTOR returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

%busActorsActorsName = strcat(busName, 'Actors');

cellInfo = { ... 
  { ... 
    busName, ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'NumActors', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Time', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Actors', [numActor 1], char(strcat("Bus: ",busActorsActorsName)), 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    char(busActorsActorsName), ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'ActorID', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Position', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Velocity', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Roll', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pitch', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Yaw', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AngularVelocity', [1 3], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

evalin('base', strcat("clear ", busName));
Simulink.Bus.cellToObject(cellInfo)